yellow_detector:
  hsv:
    low_H: 10
    low_S: 100
    low_V: 100
    high_H: 20
    high_S: 255
    high_V: 255
  
  pid:
    Kp: 0.1
    Ki: 0.003
    Kd: 0.03
    dt: 0.01
    stop_trigger_wait_time: 2.0
  
  detection:
    min_cluster_size: 100
    required_consecutive_frames: 5 